# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxAlamofileTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxAlamofileTest

  target 'RxAlamofileTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxAlamofileTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'RxAlamofire/RxCocoa'
  pod 'ObjectMapper'

end
